<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260618211305 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE SEQUENCE id INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE application (id UUID NOT NULL, name VARCHAR(255) NOT NULL, hostname VARCHAR(255) DEFAULT NULL, secret VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE application_checkpoint (application_id VARCHAR(255) NOT NULL, stream_id VARCHAR(255) NOT NULL, checkpoint BIGINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (application_id, stream_id))');
        $this->addSql('CREATE TABLE connection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id UUID NOT NULL, connected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, disconnected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, ip VARCHAR(100) NOT NULL, application_type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE event (id UUID NOT NULL, name VARCHAR(255) NOT NULL, version INT NOT NULL, retired BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, system_event BOOLEAN NOT NULL, deleted BOOLEAN NOT NULL, tombstone_after_seconds INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3BAE0AA75E237E066F61913DEB3B4E33 ON event (name, system_event, deleted)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7FCD4D86E ON event (tombstone_after_seconds)');
        $this->addSql('CREATE TABLE event_property (id UUID NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, type_class VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, contains_personal_data BOOLEAN NOT NULL, event_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD1EF50E71F7E88B ON event_property (event_id)');
        $this->addSql('CREATE TABLE mutation_condition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, parameter_values JSON NOT NULL, conditions_group_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_22F2681BE1B9916B ON mutation_condition (conditions_group_id)');
        $this->addSql('CREATE TABLE mutation_conditions_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, group_type VARCHAR(255) NOT NULL, projection_mutation_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AF673DB9E28B6131 ON mutation_conditions_group (projection_mutation_id)');
        $this->addSql('CREATE TABLE projection (id UUID NOT NULL, partition BOOLEAN NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted BOOLEAN NOT NULL, current_state JSON DEFAULT NULL, continuous BOOLEAN NOT NULL, total_number_of_events_processed INT NOT NULL, reset_total_number_of_events_processed INT NOT NULL, last_all_sequence_checkpoint_processed INT NOT NULL, condition TEXT NOT NULL, expose_state_via_api BOOLEAN NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8004C826EB3B4E33 ON projection (deleted)');
        $this->addSql('CREATE TABLE projection_mutation (id UUID NOT NULL, event_id UUID NOT NULL, projection_id UUID NOT NULL, event_property_id UUID NOT NULL, type VARCHAR(255) NOT NULL, projection_event_property_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, projection_property_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D3DEAAF689F7B20A ON projection_mutation (projection_property_id)');
        $this->addSql('CREATE INDEX event_id_idx ON projection_mutation (event_id)');
        $this->addSql('CREATE INDEX event_property_id_idx ON projection_mutation (event_property_id)');
        $this->addSql('CREATE INDEX event_property_id_and_projection_id_idx ON projection_mutation (event_property_id, projection_id)');
        $this->addSql('CREATE TABLE projection_property (id UUID NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, projection_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1765CEDE5ECF66BD ON projection_property (projection_id)');
        $this->addSql('CREATE TABLE projection_state (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stream_id VARCHAR(255) DEFAULT NULL, projection_id UUID NOT NULL, current_version BOOLEAN NOT NULL, current_state JSON DEFAULT NULL, type TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX projection_state_stream_id_idx ON projection_state (stream_id)');
        $this->addSql('CREATE INDEX projection_state_projection_id_idx ON projection_state (projection_id)');
        $this->addSql('CREATE INDEX projection_state_type_idx ON projection_state (type)');
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE runtime_error (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, error TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, public_ssh_key TEXT DEFAULT NULL, last_ssh_key_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stream (id TEXT NOT NULL, current_version INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stream_event (id UUID NOT NULL, event_id UUID NOT NULL, stream_id TEXT NOT NULL, event_name VARCHAR(255) NOT NULL, event_version INT NOT NULL, sequence INT NOT NULL, all_sequence INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tombstoned BOOLEAN NOT NULL, personal_data_has_been_encrypted BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_74C6EFCCD0ED463E ON stream_event (stream_id)');
        $this->addSql('CREATE INDEX stream_event_sequence_idx ON stream_event (sequence)');
        $this->addSql('CREATE INDEX stream_event_all_sequence_idx ON stream_event (all_sequence)');
        $this->addSql('CREATE INDEX stream_event_tombstoned_idx ON stream_event (tombstoned)');
        $this->addSql('CREATE INDEX stream_event_personal_data_has_been_encrypted_idx ON stream_event (personal_data_has_been_encrypted)');
        $this->addSql('CREATE TABLE stream_event_property (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, serialized_value TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_property_id UUID NOT NULL, stream_event_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9E4F7B49551522C6 ON stream_event_property (stream_event_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, email_auth_code VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE event_property ADD CONSTRAINT FK_CD1EF50E71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE mutation_condition ADD CONSTRAINT FK_22F2681BE1B9916B FOREIGN KEY (conditions_group_id) REFERENCES mutation_conditions_group (id)');
        $this->addSql('ALTER TABLE mutation_conditions_group ADD CONSTRAINT FK_AF673DB9E28B6131 FOREIGN KEY (projection_mutation_id) REFERENCES projection_mutation (id)');
        $this->addSql('ALTER TABLE projection_mutation ADD CONSTRAINT FK_D3DEAAF689F7B20A FOREIGN KEY (projection_property_id) REFERENCES projection_property (id)');
        $this->addSql('ALTER TABLE projection_property ADD CONSTRAINT FK_1765CEDE5ECF66BD FOREIGN KEY (projection_id) REFERENCES projection (id)');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stream_event ADD CONSTRAINT FK_74C6EFCCD0ED463E FOREIGN KEY (stream_id) REFERENCES stream (id)');
        $this->addSql('ALTER TABLE stream_event_property ADD CONSTRAINT FK_9E4F7B49551522C6 FOREIGN KEY (stream_event_id) REFERENCES stream_event (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP SEQUENCE id CASCADE');
        $this->addSql('ALTER TABLE event_property DROP CONSTRAINT FK_CD1EF50E71F7E88B');
        $this->addSql('ALTER TABLE mutation_condition DROP CONSTRAINT FK_22F2681BE1B9916B');
        $this->addSql('ALTER TABLE mutation_conditions_group DROP CONSTRAINT FK_AF673DB9E28B6131');
        $this->addSql('ALTER TABLE projection_mutation DROP CONSTRAINT FK_D3DEAAF689F7B20A');
        $this->addSql('ALTER TABLE projection_property DROP CONSTRAINT FK_1765CEDE5ECF66BD');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE stream_event DROP CONSTRAINT FK_74C6EFCCD0ED463E');
        $this->addSql('ALTER TABLE stream_event_property DROP CONSTRAINT FK_9E4F7B49551522C6');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE application_checkpoint');
        $this->addSql('DROP TABLE connection');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_property');
        $this->addSql('DROP TABLE mutation_condition');
        $this->addSql('DROP TABLE mutation_conditions_group');
        $this->addSql('DROP TABLE projection');
        $this->addSql('DROP TABLE projection_mutation');
        $this->addSql('DROP TABLE projection_property');
        $this->addSql('DROP TABLE projection_state');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE runtime_error');
        $this->addSql('DROP TABLE settings');
        $this->addSql('DROP TABLE stream');
        $this->addSql('DROP TABLE stream_event');
        $this->addSql('DROP TABLE stream_event_property');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
